#file: noinspection SpellCheckingInspection
name: Checks

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  compile:
    if: github.repository_owner == 'dawpitech'
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install go 1.23.8
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.8'
          cache: 'true'

      - name: Compile
        run: go build

  trigger-submodules-update:
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: Trigger Main Repository CI/CD
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.PAT_SURVIVOR }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            https://api.github.com/repos/dawpitech/survivor/dispatches \
            -d '{"event_type": "update_submodule"}'